### ISSUE TITLE
Add Cake Addin to Website

### ISSUE THREAD

**Issue by gep13** [Kemyke/Cake.Nuget.Versioning#1]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by Kemyke** [comment]
I created a new package with version 0.0.7. Please check if the documentation is appropriate.

**Comment by Kemyke** [comment]
https://github.com/cake-build/website/pull/442

**Comment by gep13** [comment]
@Kemyke thank you for doing this!
