### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [Kemyke/Cake.Nuget.Versioning#2]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by Kemyke** [comment]
Sure, i am really glad to contribute and add value to the community. I'll read the docs what to do.

I also wrote a tfs variable evaluator which you can find on my github. Please take a look, if you think that might be useful for others, i could also add that library.

**Comment by gep13** [comment]
Yes, that would be perfect.  There wasn't a link on the NuGet Package to the GitHub repository (must be missing from the nuspec file), and I didn't go and find it.  I will raise issues in that repo for tracking the addition as well.  Thanks.

**Comment by gep13** [comment]
@Kemyke thanks for doing this! :+1:
